[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[window]
opacity = 1.0

[window.class]
general = "Alacritty"
instance = "Alacritty"
